<h1><font color='blue'>Análise de Sentimentos e Sistemas de Recomendação</font></h1>
<h2><b>Prática U1-T2-V2.2-Abordagens baseadas em léxico</b></h2>


---

## Preparação

### Carregando o dataset

In [1]:
import pandas as pd
df = pd.read_csv('https://drive.google.com/uc?export=download&id=1M7VtNfEh7K3gqa4OiWiayPkg8q6x8fXk', encoding='utf-8', low_memory=False)
df.head()

,frase_pt,frase_en,sentimento
0,O atendimento ao cliente foi excepcional e res...,The customer service was exceptional and solve...,Positivo
1,"Este é, sem dúvida, o melhor café que já prove...","This is, without a doubt, the best coffee I've...",Positivo
2,O filme tem uma fotografia incrível e uma tril...,The movie has incredible cinematography and a ...,Positivo
3,Estou muito satisfeito com a qualidade do prod...,I am very satisfied with the product's quality...,Positivo
4,A equipe foi extremamente simpática e prestati...,The staff was extremely friendly and helpful t...,Positivo

In [2]:
df['sentimento'].value_counts()

sentimento
Positivo    10
Negativo    10
Neutro      10
Name: count, dtype: int64

### Pré-processamento do texto

In [3]:
import nltk

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

True

In [4]:
import re
from nltk.tokenize import word_tokenize
import unicodedata

def preprocess(text):
    text = text.lower()
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokens = word_tokenize(text)
    return tokens

preprocess('O trânsito      HOJE estava    $$$ %  &  #simplesmente insuportável.')

['o', 'transito', 'hoje', 'estava', 'simplesmente', 'insuportavel']

## Abordagem usando VADER

### 📘 O léxico VADER (vader_lexicon)

#### O que é o VADER?
O **VADER (Valence Aware Dictionary and sEntiment Reasoner)** é um dicionário léxico desenvolvido especificamente para **análise de sentimentos em textos curtos e informais**, como comentários em redes sociais, avaliações online e mensagens instantâneas.

Diferente de léxicos tradicionais, o VADER foi criado levando em conta **a forma como as pessoas realmente escrevem na internet**, incluindo gírias, pontuação e emojis.

---

#### 🎯 Principais Características

- Léxico **pré-definido** com palavras associadas a sentimentos
- Cada termo possui um **valor de polaridade** (positivo ou negativo)
- Sensível a **intensidade emocional**
- Especialmente eficaz para textos curtos
- Muito utilizado como **baseline** em projetos de PLN

---

#### 🧮 Como o vader_lexicon funciona

O VADER atribui uma **pontuação de sentimento** às palavras e ajusta essa pontuação considerando regras heurísticas, como:

- **Intensificadores**  
  Ex.: *"muito bom"* → sentimento mais forte

- **Negação**  
  Ex.: *"não gostei"* → inversão da polaridade

- **Pontuação**  
  Ex.: *"excelente!!!"* → maior intensidade

- **Uso de MAIÚSCULAS**  
  Ex.: *"ÓTIMO"* → ênfase emocional

- **Emojis e emoticons**  
  Ex.: 😄 😡

---

#### 📊 Saída do VADER

O VADER retorna quatro métricas principais:

- **pos** → proporção de sentimento positivo
- **neg** → proporção de sentimento negativo
- **neu** → proporção neutra
- **compoun**

In [5]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [6]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores("I really love this movie. It's fantastic!")

{'neg': 0.0, 'neu': 0.323, 'pos': 0.677, 'compound': 0.855}

In [7]:
def retorna_sentimento(vader_scores):
    pos = vader_scores.get("pos", 0)
    neg = vader_scores.get("neg", 0)
    neu = vader_scores.get("neu", 0)

    if pos > neg and pos > neu:
        return "Positivo"
    elif neg > pos and neg > neu:
        return "Negativo"
    else:
        return "Neutro"

In [8]:
frases = df['frase_en'].values.tolist()
frases[:5]

['The customer service was exceptional and solved my problem quickly.',
 "This is, without a doubt, the best coffee I've ever tasted in the city!",
 'The movie has incredible cinematography and a moving soundtrack.',
 "I am very satisfied with the product's quality, it exceeded my expectations.",
 'The staff was extremely friendly and helpful throughout my entire visit.']

In [9]:
res = analyzer.polarity_scores('The customer service was exceptional and solved my problem quickly.')
print(res)
retorna_sentimento(res)

{'neg': 0.211, 'neu': 0.625, 'pos': 0.164, 'compound': -0.1531}

'Neutro'

In [10]:
# Criar uma instância do analisador de sentimento
analyzer = SentimentIntensityAnalyzer()

# Analisar o sentimento de cada frase
y_pred = []
for frase, sentimento in df[['frase_en','sentimento']].values.tolist():
    res = analyzer.polarity_scores(frase)
    # Determinar o sentimento geral com base na pontuação composta
    retorno = retorna_sentimento(res)
    y_pred.append(retorno)
    print(f'Frase: {frase:<90} - Sentimento: pred "{retorno}" - real "{sentimento}" \n\t{res}')

Frase: The customer service was exceptional and solved my problem quickly.                        - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.211, 'neu': 0.625, 'pos': 0.164, 'compound': -0.1531}
Frase: This is, without a doubt, the best coffee I've ever tasted in the city!                    - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.218, 'neu': 0.656, 'pos': 0.126, 'compound': -0.3716}
Frase: The movie has incredible cinematography and a moving soundtrack.                           - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: I am very satisfied with the product's quality, it exceeded my expectations.               - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.764, 'pos': 0.236, 'compound': 0.4754}
Frase: The staff was extremely friendly and helpful throughout my entire visit.                   - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.579, 'pos': 0.421, 'compound': 0.762}
Frase: What a wonderful experience! I will definitely be back for more.                           - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.511, 'pos': 0.489, 'compound': 0.7712}
Frase: The book arrived in perfect condition and ahead of schedule. I recommend it!               - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.606, 'pos': 0.394, 'compound': 0.7574}
Frase: The view from the hotel room is absolutely stunning.                                       - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.734, 'pos': 0.266, 'compound': 0.4391}
Frase: I loved the new feature in the app, it became much easier to use.                          - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.621, 'pos': 0.379, 'compound': 0.7717}
Frase: The show was spectacular, a contagious energy from start to finish.                        - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.192, 'neu': 0.64, 'pos': 0.168, 'compound': -0.0772}
Frase: The product arrived broken and the packaging was all crumpled.                             - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.256, 'neu': 0.744, 'pos': 0.0, 'compound': -0.4767}
Frase: I am deeply disappointed with the service provided, I do not recommend it.                 - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.379, 'neu': 0.621, 'pos': 0.0, 'compound': -0.6708}
Frase: The food was cold and the waiter took forever to serve us.                                 - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: What a terrible movie, the script is weak and the acting is awful.                         - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.5, 'neu': 0.5, 'pos': 0.0, 'compound': -0.8402}
Frase: The internet signal drops all the time, it's impossible to work like this.                 - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'compound': 0.3612}
Frase: I didn't like the series finale, I thought it ruined the whole story.                      - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.367, 'neu': 0.633, 'pos': 0.0, 'compound': -0.6381}
Frase: A terrible shopping experience, the website is confusing and the support doesn't help.     - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.404, 'neu': 0.445, 'pos': 0.15, 'compound': -0.5511}
Frase: The traffic today was simply unbearable.                                                   - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: A two-hour queue for a mediocre service. Of course, I 'loved' the experience.              - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The app constantly freezes and closes by itself, very frustrating.                         - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.349, 'neu': 0.651, 'pos': 0.0, 'compound': -0.5095}
Frase: The event is scheduled for next Tuesday at 7 PM.                                           - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The quarterly financial report was presented at the meeting.                               - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The flight from Belo Horizonte to São Paulo lasts approximately one hour.                  - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: This document contains the product's technical specifications.                             - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The car's color is gray and it has four doors.                                             - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The film is an adaptation of a book published in 1985.                                     - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: To access the system, the user must enter a login and password.                            - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The phone's battery lasts all day with moderate use.                                       - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The delivery was made to the agreed-upon address, as per the order.                        - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The restaurant serves Italian cuisine, but the price is high.                              - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

Ver a taxa de acerto (acurácia)

In [11]:
from sklearn.metrics import accuracy_score

y_true = df['sentimento'].values.tolist()
accuracy_score(y_true, y_pred)

0.3333333333333333

In [12]:
def retorna_sentimento(vader_scores, limiar_compound=0.05, limiar_neutro=0.8):
    neg = vader_scores.get("neg", 0)
    neu = vader_scores.get("neu", 0)
    pos = vader_scores.get("pos", 0)
    compound = vader_scores.get("compound", 0)

    # Predominância de neutralidade
    if neu >= limiar_neutro:
        return "Neutro"
    # Decisão baseada no compound
    elif compound >= limiar_compound and pos > neg:
        return "Positivo"
    elif compound <= -limiar_compound and neg > pos:
        return "Negativo"
    else:
        return "Neutro"

In [13]:
# Criar uma instância do analisador de sentimento
analyzer = SentimentIntensityAnalyzer()

# Analisar o sentimento de cada frase
y_pred = []
for frase, sentimento in df[['frase_en','sentimento']].values.tolist():
    res = analyzer.polarity_scores(frase)
    # Determinar o sentimento geral com base na pontuação composta
    retorno = retorna_sentimento(res)
    y_pred.append(retorno)
    print(f'Frase: {frase:<90} - Sentimento: pred "{retorno}" - real "{sentimento}" \n\t{res}')

Frase: The customer service was exceptional and solved my problem quickly.                        - Sentimento: pred "Negativo" - real "Positivo"
	{'neg': 0.211, 'neu': 0.625, 'pos': 0.164, 'compound': -0.1531}
Frase: This is, without a doubt, the best coffee I've ever tasted in the city!                    - Sentimento: pred "Negativo" - real "Positivo"
	{'neg': 0.218, 'neu': 0.656, 'pos': 0.126, 'compound': -0.3716}
Frase: The movie has incredible cinematography and a moving soundtrack.                           - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: I am very satisfied with the product's quality, it exceeded my expectations.               - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.764, 'pos': 0.236, 'compound': 0.4754}
Frase: The staff was extremely friendly and helpful throughout my entire visit.                   - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.579, 'pos': 0.421, 'compound': 0.762}
Frase: What a wonderful experience! I will definitely be back for more.                           - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.511, 'pos': 0.489, 'compound': 0.7712}
Frase: The book arrived in perfect condition and ahead of schedule. I recommend it!               - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.606, 'pos': 0.394, 'compound': 0.7574}
Frase: The view from the hotel room is absolutely stunning.                                       - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.734, 'pos': 0.266, 'compound': 0.4391}
Frase: I loved the new feature in the app, it became much easier to use.                          - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.621, 'pos': 0.379, 'compound': 0.7717}
Frase: The show was spectacular, a contagious energy from start to finish.                        - Sentimento: pred "Negativo" - real "Positivo"
	{'neg': 0.192, 'neu': 0.64, 'pos': 0.168, 'compound': -0.0772}
Frase: The product arrived broken and the packaging was all crumpled.                             - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.256, 'neu': 0.744, 'pos': 0.0, 'compound': -0.4767}
Frase: I am deeply disappointed with the service provided, I do not recommend it.                 - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.379, 'neu': 0.621, 'pos': 0.0, 'compound': -0.6708}
Frase: The food was cold and the waiter took forever to serve us.                                 - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: What a terrible movie, the script is weak and the acting is awful.                         - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.5, 'neu': 0.5, 'pos': 0.0, 'compound': -0.8402}
Frase: The internet signal drops all the time, it's impossible to work like this.                 - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'compound': 0.3612}
Frase: I didn't like the series finale, I thought it ruined the whole story.                      - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.367, 'neu': 0.633, 'pos': 0.0, 'compound': -0.6381}
Frase: A terrible shopping experience, the website is confusing and the support doesn't help.     - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.404, 'neu': 0.445, 'pos': 0.15, 'compound': -0.5511}
Frase: The traffic today was simply unbearable.                                                   - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: A two-hour queue for a mediocre service. Of course, I 'loved' the experience.              - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The app constantly freezes and closes by itself, very frustrating.                         - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.349, 'neu': 0.651, 'pos': 0.0, 'compound': -0.5095}
Frase: The event is scheduled for next Tuesday at 7 PM.                                           - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The quarterly financial report was presented at the meeting.                               - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The flight from Belo Horizonte to São Paulo lasts approximately one hour.                  - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: This document contains the product's technical specifications.                             - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The car's color is gray and it has four doors.                                             - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The film is an adaptation of a book published in 1985.                                     - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: To access the system, the user must enter a login and password.                            - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The phone's battery lasts all day with moderate use.                                       - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The delivery was made to the agreed-upon address, as per the order.                        - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: The restaurant serves Italian cuisine, but the price is high.                              - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [14]:
accuracy_score(y_true, y_pred)

0.7333333333333333

### 📘 LeIA (Lexicon-based Sentiment Analysis for Portuguese)

A **LeIA** é uma biblioteca de **análise de sentimentos baseada em léxico**, desenvolvida especificamente para o **português**, com foco no **português brasileiro**. Seu objetivo é identificar a **polaridade emocional** de textos curtos, como comentários, avaliações e postagens em redes sociais.

Inspirada no **VADER**, a LeIA combina um **dicionário de palavras com escores de sentimento** e um conjunto de **regras linguísticas** que modelam fenômenos comuns da linguagem natural, como **negação**, **intensificadores**, **pontuação**, **uso de emojis** e expressões coloquiais do português.

A biblioteca retorna um **dicionário de pontuações**, contendo os valores:
- **pos**: intensidade do sentimento positivo
- **neg**: intensidade do sentimento negativo
- **neu**: intensidade do sentimento neutro
- **compound**: escore global normalizado do sentimento

A LeIA é amplamente utilizada em **contextos educacionais**, **monitoramento de opiniões**, **análise de feedbacks** e **prototipagem rápida**, sendo uma solução eficiente quando não há grandes volumes de dados rotulados para treinamento de modelos de machine learning.

In [15]:
!pip install -q leia-br

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 4.0 MB/s eta 0:00:00

In [16]:
from LeIA import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores('O atendimento ao cliente foi excepcional e resolveu meu problema rapidamente.')

{'neg': 0.181, 'neu': 0.403, 'pos': 0.416, 'compound': 0.5423}

In [17]:
# Criar uma instância do analisador de sentimento
analyzer = SentimentIntensityAnalyzer()

# Analisar o sentimento de cada frase
y_pred = []
for frase, sentimento in df[['frase_pt','sentimento']].values.tolist():
    res = analyzer.polarity_scores(frase)
    # Determinar o sentimento geral com base na pontuação composta
    retorno = retorna_sentimento(res)
    y_pred.append(retorno)
    print(f'Frase: {frase:<90} - Sentimento: pred "{retorno}" - real "{sentimento}" \n\t{res}')

Frase: O atendimento ao cliente foi excepcional e resolveu meu problema rapidamente.              - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.181, 'neu': 0.403, 'pos': 0.416, 'compound': 0.5423}
Frase: Este é, sem dúvida, o melhor café que já provei na cidade!                                 - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.153, 'neu': 0.625, 'pos': 0.222, 'compound': 0.2481}
Frase: O filme tem uma fotografia incrível e uma trilha sonora emocionante.                       - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.721, 'pos': 0.279, 'compound': 0.4767}
Frase: Estou muito satisfeito com a qualidade do produto, superou minhas expectativas.            - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.763, 'pos': 0.237, 'compound': 0.4215}
Frase: A equipe foi extremamente simpática e prestativa durante toda a minha visita.              - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: Que experiência maravilhosa! Com certeza voltarei mais vezes.                              - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.492, 'pos': 0.508, 'compound': 0.7345}
Frase: O livro chegou em perfeito estado e antes do prazo. Recomendo!                             - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.579, 'pos': 0.421, 'compound': 0.6239}
Frase: A vista do quarto do hotel é absolutamente deslumbrante.                                   - Sentimento: pred "Negativo" - real "Positivo"
	{'neg': 0.249, 'neu': 0.751, 'pos': 0.0, 'compound': -0.2484}
Frase: Adorei a nova funcionalidade do aplicativo, ficou muito mais fácil de usar.                - Sentimento: pred "Positivo" - real "Positivo"
	{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'compound': 0.4404}
Frase: O show foi espetacular, uma energia contagiante do início ao fim.                          - Sentimento: pred "Neutro" - real "Positivo"
	{'neg': 0.0, 'neu': 0.804, 'pos': 0.196, 'compound': 0.296}
Frase: O produto chegou quebrado e a embalagem estava toda amassada.                              - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.341, 'neu': 0.659, 'pos': 0.0, 'compound': -0.4767}
Frase: Estou profundamente decepcionado com o serviço prestado, não recomendo.                    - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.409, 'neu': 0.394, 'pos': 0.197, 'compound': -0.4005}
Frase: A comida estava fria e o garçom demorou uma eternidade para nos atender.                   - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.151, 'neu': 0.849, 'pos': 0.0, 'compound': -0.1531}
Frase: Que filme terrível, o roteiro é fraco e as atuações são péssimas.                          - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.435, 'neu': 0.565, 'pos': 0.0, 'compound': -0.6597}
Frase: O sinal da internet cai o tempo todo, é impossível trabalhar assim.                        - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: Não gostei do final da série, achei que estragou toda a história.                          - Sentimento: pred "Positivo" - real "Negativo"
	{'neg': 0.157, 'neu': 0.643, 'pos': 0.2, 'compound': 0.1531}
Frase: Péssima experiência de compra, o site é confuso e o suporte não ajuda.                     - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.323, 'neu': 0.472, 'pos': 0.205, 'compound': -0.128}
Frase: O trânsito hoje estava simplesmente insuportável.                                          - Sentimento: pred "Neutro" - real "Negativo"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: Fila de duas horas para um serviço medíocre. Claro, adorei a experiência.                  - Sentimento: pred "Positivo" - real "Negativo"
	{'neg': 0.121, 'neu': 0.682, 'pos': 0.197, 'compound': 0.25}
Frase: O aplicativo trava constantemente e fecha sozinho, muito frustrante.                       - Sentimento: pred "Negativo" - real "Negativo"
	{'neg': 0.495, 'neu': 0.505, 'pos': 0.0, 'compound': -0.5994}
Frase: O evento está agendado para a próxima terça-feira, às 19h.                                 - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.186, 'neu': 0.814, 'pos': 0.0, 'compound': -0.1531}
Frase: O relatório financeiro do trimestre foi apresentado na reunião.                            - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: O voo de Belo Horizonte para São Paulo tem duração de aproximadamente uma hora.            - Sentimento: pred "Positivo" - real "Neutro"
	{'neg': 0.105, 'neu': 0.724, 'pos': 0.171, 'compound': 0.25}
Frase: Este documento contém as especificações técnicas do produto.                               - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: A cor do carro é cinza e ele tem quatro portas.                                            - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: O filme é uma adaptação de um livro publicado em 1985.                                     - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: Para acessar o sistema, o usuário precisa inserir login e senha.                           - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.186, 'neu': 0.814, 'pos': 0.0, 'compound': -0.1531}
Frase: A bateria do celular dura o dia todo com uso moderado.                                     - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: A entrega foi feita no endereço combinado, conforme o pedido.                              - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Frase: O restaurante serve pratos da culinária italiana, mas o preço é elevado.                   - Sentimento: pred "Neutro" - real "Neutro"
	{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [18]:
accuracy_score(y_true, y_pred)

0.7

## Abordagem usando TextBlob

### 📘 TextBlob

O **TextBlob** é uma biblioteca de **Processamento de Linguagem Natural (PLN)** em Python que oferece funcionalidades simples e acessíveis para tarefas como **análise de sentimentos**, **tokenização**, **extração de n-gramas**, **tradução** e **classificação de texto**. Sua proposta principal é facilitar o uso de técnicas de PLN, especialmente em contextos educacionais e de prototipagem.

Na análise de sentimentos, o TextBlob utiliza uma abordagem **baseada em léxico**, apoiada no léxico **Pattern**, que associa palavras a valores de **polaridade** e **subjetividade**. A polaridade indica o quão positiva ou negativa é uma opinião, enquanto a subjetividade mede o grau de opinião versus fato presente no texto.

A saída do TextBlob é composta principalmente por dois valores:
- **polarity**: varia de -1 (negativo) a +1 (positivo)
- **subjectivity**: varia de 0 (objetivo) a 1 (subjetivo)

O TextBlob é amplamente utilizado para **análises rápidas**, **demonstrações em sala de aula** e **projetos iniciais**, sendo uma ferramenta intuitiva para introduzir conceitos fundamentais de análise de sentimentos, embora apresente limitações em textos complexos, irônicos ou fora do domínio do inglês.

In [19]:
from textblob import TextBlob

res = TextBlob('The customer service was exceptional and solved my problem quickly.')
res.sentiment

Sentiment(polarity=0.5, subjectivity=0.75)

In [20]:
def retorna_sentimento(sentiment):
    polarity = sentiment.polarity

    if polarity > 0:
        return "Positivo"
    elif polarity < 0:
        return "Negativo"
    else:
        return "Neutro"

retorna_sentimento(res.sentiment)

'Positivo'

In [21]:
y_pred = []
for frase, sentimento in df[['frase_en','sentimento']].values.tolist():
    res = TextBlob(frase)
    # Determinar o sentimento geral com base na pontuação composta
    retorno = retorna_sentimento(res.sentiment)
    y_pred.append(retorno)
    print(f'Frase: {frase:<90} - Sentimento: pred "{retorno}" - real "{sentimento}" \n\t{res.sentiment}')

Frase: The customer service was exceptional and solved my problem quickly.                        - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.5, subjectivity=0.75)
Frase: This is, without a doubt, the best coffee I've ever tasted in the city!                    - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=1.0, subjectivity=0.3)
Frase: The movie has incredible cinematography and a moving soundtrack.                           - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.9, subjectivity=0.9)
Frase: I am very satisfied with the product's quality, it exceeded my expectations.               - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.65, subjectivity=1.0)
Frase: The staff was extremely friendly and helpful throughout my entire visit.                   - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.1875, subjectivity=0.5625)
Frase: What a wonderful experience! I will definitely be back for more.                           - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.5, subjectivity=0.5)
Frase: The book arrived in perfect condition and ahead of schedule. I recommend it!               - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=1.0, subjectivity=1.0)
Frase: The view from the hotel room is absolutely stunning.                                       - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.5, subjectivity=1.0)
Frase: I loved the new feature in the app, it became much easier to use.                          - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.34545454545454546, subjectivity=0.48484848484848486)
Frase: The show was spectacular, a contagious energy from start to finish.                        - Sentimento: pred "Positivo" - real "Positivo"
	Sentiment(polarity=0.6, subjectivity=0.9)
Frase: The product arrived broken and the packaging was all crumpled.                             - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.4, subjectivity=0.4)
Frase: I am deeply disappointed with the service provided, I do not recommend it.                 - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.75, subjectivity=0.75)
Frase: The food was cold and the waiter took forever to serve us.                                 - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.6, subjectivity=1.0)
Frase: What a terrible movie, the script is weak and the acting is awful.                         - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.59375, subjectivity=0.65625)
Frase: The internet signal drops all the time, it's impossible to work like this.                 - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.6666666666666666, subjectivity=1.0)
Frase: I didn't like the series finale, I thought it ruined the whole story.                      - Sentimento: pred "Positivo" - real "Negativo"
	Sentiment(polarity=0.2, subjectivity=0.4)
Frase: A terrible shopping experience, the website is confusing and the support doesn't help.     - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.65, subjectivity=0.7)
Frase: The traffic today was simply unbearable.                                                   - Sentimento: pred "Neutro" - real "Negativo"
	Sentiment(polarity=0.0, subjectivity=0.35714285714285715)
Frase: A two-hour queue for a mediocre service. Of course, I 'loved' the experience.              - Sentimento: pred "Positivo" - real "Negativo"
	Sentiment(polarity=0.09999999999999998, subjectivity=0.9)
Frase: The app constantly freezes and closes by itself, very frustrating.                         - Sentimento: pred "Negativo" - real "Negativo"
	Sentiment(polarity=-0.26, subjectivity=0.6666666666666666)
Frase: The event is scheduled for next Tuesday at 7 PM.                                           - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.0)
Frase: The quarterly financial report was presented at the meeting.                               - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.0)
Frase: The flight from Belo Horizonte to São Paulo lasts approximately one hour.                  - Sentimento: pred "Negativo" - real "Neutro"
	Sentiment(polarity=-0.4, subjectivity=0.6)
Frase: This document contains the product's technical specifications.                             - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.1)
Frase: The car's color is gray and it has four doors.                                             - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.0)
Frase: The film is an adaptation of a book published in 1985.                                     - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.0)
Frase: To access the system, the user must enter a login and password.                            - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.0)
Frase: The phone's battery lasts all day with moderate use.                                       - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.7)
Frase: The delivery was made to the agreed-upon address, as per the order.                        - Sentimento: pred "Neutro" - real "Neutro"
	Sentiment(polarity=0.0, subjectivity=0.0)
Frase: The restaurant serves Italian cuisine, but the price is high.                              - Sentimento: pred "Positivo" - real "Neutro"
	Sentiment(polarity=0.08, subjectivity=0.27)

In [22]:
accuracy_score(y_true, y_pred)

0.8333333333333334